
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'project_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'project_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["project_dbt/models"]
analysis-paths: ["project_dbt/analyses"]
test-paths: ["project_dbt/tests"]
seed-paths: ["project_dbt/seeds"]
macro-paths: ["project_dbt/macros"]
snapshot-paths: ["project_dbt/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.


# test
models:

  project_dbt:
    example:
      +materialized: view

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table